// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ask.proto

package com.grpc.ej3;

public final class AskProto {
  private AskProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Pregunta_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Pregunta_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Respuesta_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Respuesta_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\task.proto\"\033\n\010Pregunta\022\017\n\007mensaje\030\001 \001(\t" +
      "\"\034\n\tRespuesta\022\017\n\007mensaje\030\001 \001(\t20\n\nAskSer" +
      "vice\022\"\n\tpreguntar\022\t.Pregunta\032\n.Respuesta" +
      "25\n\017ResponseService\022\"\n\tresponder\022\t.Pregu" +
      "nta\032\n.RespuestaB\032\n\014com.grpc.ej3B\010AskProt" +
      "oP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Pregunta_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Pregunta_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Pregunta_descriptor,
        new java.lang.String[] { "Mensaje", });
    internal_static_Respuesta_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Respuesta_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Respuesta_descriptor,
        new java.lang.String[] { "Mensaje", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
