// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ask.proto

package com.grpc.ej3;

public interface RespuestaOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Respuesta)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string mensaje = 1;</code>
   * @return The mensaje.
   */
  java.lang.String getMensaje();
  /**
   * <code>string mensaje = 1;</code>
   * @return The bytes for mensaje.
   */
  com.google.protobuf.ByteString
      getMensajeBytes();
}
