// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: product.proto

package com.grpc.ej5;

public interface InsertSummaryOrBuilder extends
    // @@protoc_insertion_point(interface_extends:InsertSummary)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 insertedCount = 1;</code>
   * @return The insertedCount.
   */
  int getInsertedCount();
}
