// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: product.proto

package com.grpc.ej5;

public interface PriceRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PriceRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double maxPrice = 1;</code>
   * @return The maxPrice.
   */
  double getMaxPrice();
}
