// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: product.proto

package com.grpc.ej5;

public interface ProductIdRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ProductIdRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  int getId();
}
