// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: product.proto

package com.grpc.ej5;

public final class ProductProto {
  private ProductProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ProductIdRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ProductIdRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PriceRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PriceRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ProductResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ProductResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_NewProductRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_NewProductRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_InsertSummary_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_InsertSummary_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rproduct.proto\"\036\n\020ProductIdRequest\022\n\n\002i" +
      "d\030\001 \001(\005\" \n\014PriceRequest\022\020\n\010maxPrice\030\001 \001(" +
      "\001\":\n\017ProductResponse\022\n\n\002id\030\001 \001(\005\022\014\n\004name" +
      "\030\002 \001(\t\022\r\n\005price\030\003 \001(\001\"0\n\021NewProductReque" +
      "st\022\014\n\004name\030\001 \001(\t\022\r\n\005price\030\002 \001(\001\"&\n\rInser" +
      "tSummary\022\025\n\rinsertedCount\030\001 \001(\0052\362\001\n\016Prod" +
      "uctService\0225\n\016GetProductById\022\021.ProductId" +
      "Request\032\020.ProductResponse\022:\n\025StreamCheap" +
      "erProducts\022\r.PriceRequest\032\020.ProductRespo" +
      "nse0\001\0226\n\016InsertProducts\022\022.NewProductRequ" +
      "est\032\016.InsertSummary(\001\0225\n\016LivePriceQuery\022" +
      "\r.PriceRequest\032\020.ProductResponse(\0010\001B\036\n\014" +
      "com.grpc.ej5B\014ProductProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_ProductIdRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ProductIdRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ProductIdRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_PriceRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_PriceRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PriceRequest_descriptor,
        new java.lang.String[] { "MaxPrice", });
    internal_static_ProductResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_ProductResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ProductResponse_descriptor,
        new java.lang.String[] { "Id", "Name", "Price", });
    internal_static_NewProductRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_NewProductRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_NewProductRequest_descriptor,
        new java.lang.String[] { "Name", "Price", });
    internal_static_InsertSummary_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_InsertSummary_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_InsertSummary_descriptor,
        new java.lang.String[] { "InsertedCount", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
